variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

stages:
  - build
  
build:
  stage: build
  image: docker:dind
  services:
   - docker:dind
  script:
    - docker build -t reproducer-testcontainer .